// Generated by Wrangler by running `wrangler types`
// After adding bindings to `wrangler.jsonc`, regenerate this interface with `npm run cf-typegen`
declare namespace Cloudflare {
	interface Env {
		MY_BUCKET: R2Bucket;
	}
}
interface Env extends Cloudflare.Env {}

